// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AkarIconsInfo: typeof import('~icons/akar-icons/info')['default']
    AkarIconsTriangleAlert: typeof import('~icons/akar-icons/triangle-alert')['default']
    BiX: typeof import('~icons/bi/x')['default']
    Button: typeof import('./components/Button.vue')['default']
    BxBxErrorCircle: typeof import('~icons/bx/bx-error-circle')['default']
    BxDownload: typeof import('~icons/bx/download')['default']
    CarbonHome: typeof import('~icons/carbon/home')['default']
    CodiconChromeMaximize: typeof import('~icons/codicon/chrome-maximize')['default']
    CodiconChromeMinimize: typeof import('~icons/codicon/chrome-minimize')['default']
    CommandBox: typeof import('./components/commands/CommandBox.vue')['default']
    DataLoader: typeof import('./components/DataLoader.vue')['default']
    ElectronVersions: typeof import('./components/ElectronVersions.vue')['default']
    Navigation: typeof import('./components/nav/Navigation.vue')['default']
    NavigationLink: typeof import('./components/nav/NavigationLink.vue')['default']
    ReactiveCounter: typeof import('./components/ReactiveCounter.vue')['default']
    ReactiveHash: typeof import('./components/ReactiveHash.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
    Toast: typeof import('./components/toasts/Toast.vue')['default']
    ToastDispatcher: typeof import('./components/toasts/ToastDispatcher.vue')['default']
  }
}

export { }
